version: '3'

services:

  app:
    image: portfolio
    container_name: portfolio
    build: .
    user: root
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/usr/src/app
    environment:
      - NODE_ENV=${NODE_ENV}
